name: Mirror to GitLab
on: [push, delete]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          # Fixed format: https://username:token@gitlab.com/username/repo.git
          target_repo_url: https://jackson29382938:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jackson29382938/peptide_map.git